version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:

      MASTER_DB_HOST_NAME: db
      MASTER_DB_PORT: 5432

    ports:
      - "8005:8005"

    depends_on:
      db:
        condition:  service_healthy
    restart:  unless-stopped
  db:
    image: postgres:16-alpine
    environment:
      #database environment variables
      POSTGRES_DB:  ${MASTER_DB_NAME:-postgres}
      POSTGRES_USER:  ${MASTER_DB_OWNER:-postgres}
      POSTGRES_PASSWORD:  ${MASTER_PASSWORD:-postgres}
    
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    restart:  unless-stopped

volumes:
  pgdata:
